# Generated by Django 5.2.7 on 2025-10-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cliente_notaio_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaio',
            name='partita_iva',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partita_iva',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
