# Generated by Django 5.2.7 on 2025-10-21 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTypeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Codice identificativo (es: rogito, consulenza)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nome della tipologia (es: Rogito Notarile)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrizione del servizio')),
                ('default_duration_minutes', models.IntegerField(default=30, help_text='Durata suggerita in minuti')),
                ('icon', models.CharField(default='Calendar', help_text='Nome icona Lucide React (es: FileSignature, Users, Calendar)', max_length=50)),
                ('color', models.CharField(default='#4FADFF', help_text='Colore hex per il badge (es: #4FADFF)', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Ordine di visualizzazione')),
                ('is_active', models.BooleanField(default=True, help_text='Se disattivato non sarà visibile ai notai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipologia Appuntamento',
                'verbose_name_plural': 'Tipologie Appuntamenti',
                'db_table': 'appointment_type_templates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
