# Generated by Django 5.2.7 on 2025-10-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
        ('ui_elements', '0002_appointmenttypetemplate_delete_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttypetemplate',
            name='tipologie_atto',
            field=models.ManyToManyField(blank=True, help_text='Tipologie di atto associate a questo tipo di appuntamento', related_name='appointment_types', to='acts.notarialactcategory'),
        ),
    ]
