# Generated by Django 5.2.7 on 2025-10-17 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fiscal_code', models.CharField(blank=True, max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('pec_address', models.EmailField(blank=True, max_length=254)),
                ('residence_street', models.CharField(blank=True, max_length=255)),
                ('residence_city', models.CharField(blank=True, max_length=100)),
                ('residence_province', models.CharField(blank=True, max_length=50)),
                ('residence_cap', models.CharField(blank=True, max_length=10)),
                ('residence_country', models.CharField(default='Italia', max_length=50)),
                ('identity_document_type', models.CharField(blank=True, max_length=50)),
                ('identity_document_number', models.CharField(blank=True, max_length=100)),
                ('identity_document_expiry', models.DateField(blank=True, null=True)),
                ('identity_document_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Notary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('studio_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('pec_address', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_province', models.CharField(blank=True, max_length=50)),
                ('address_cap', models.CharField(blank=True, max_length=10)),
                ('address_country', models.CharField(default='Italia', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cover_image_url', models.TextField(blank=True)),
                ('profile_image_url', models.TextField(blank=True)),
                ('services', models.JSONField(blank=True, default=list, help_text='[{"name": "Compravendita", "price": 1500, "description": "..."}, ...]')),
                ('tariffe', models.JSONField(blank=True, default=dict)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_acts', models.IntegerField(default=0)),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='{"monday": {"start": "09:00", "end": "18:00"}, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notary_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notary',
                'verbose_name_plural': 'Notaries',
                'db_table': 'notaries',
                'ordering': ['-average_rating', '-total_reviews'],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='{"can_create_acts": true, "can_sign": false, "can_manage_clients": true, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_profile', to=settings.AUTH_USER_MODEL)),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='notaries.notary')),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
                'db_table': 'collaborators',
                'ordering': ['notary', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='NotaryAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Domenica'), (1, 'Lunedì'), (2, 'Martedì'), (3, 'Mercoledì'), (4, 'Giovedì'), (5, 'Venerdì'), (6, 'Sabato')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='notaries.notary')),
            ],
            options={
                'verbose_name': 'Notary Availability',
                'verbose_name_plural': 'Notary Availabilities',
                'db_table': 'notary_availability',
                'ordering': ['notary', 'day_of_week', 'start_time'],
                'unique_together': {('notary', 'day_of_week', 'start_time')},
            },
        ),
    ]
