# Generated by Django 5.2.7 on 2025-10-17 17:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notary',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
