# Generated by Django 5.2.7 on 2025-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaries', '0002_notary_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notary',
            name='showcase_availability_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='showcase_availability_hours',
            field=models.CharField(blank=True, default='Lun-Ven 9:00-18:00', max_length=100),
        ),
        migrations.AddField(
            model_name='notary',
            name='showcase_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='showcase_experience',
            field=models.IntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='notary',
            name='showcase_languages',
            field=models.CharField(blank=True, default='Italiano', max_length=255),
        ),
        migrations.AddField(
            model_name='notary',
            name='showcase_photo',
            field=models.TextField(blank=True, help_text='Base64 encoded photo for public showcase'),
        ),
        migrations.AddField(
            model_name='notary',
            name='showcase_services',
            field=models.JSONField(blank=True, default=dict, help_text='{"documents": true, "agenda": true, "chat": true, "acts": true, "signature": true, "pec": true, "conservation": true}'),
        ),
    ]
