# Generated by Django 5.2.7 on 2025-10-19 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaries', '0003_notary_showcase_availability_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('rogito', 'Rogito Notarile'), ('consulenza', 'Consulenza'), ('revisione', 'Revisione Documenti'), ('altro', 'Altro')], default='consulenza', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(help_text='Durata in minuti')),
                ('status', models.CharField(choices=[('pending', 'In attesa di conferma'), ('accepted', 'Confermato'), ('rejected', 'Rifiutato'), ('cancelled', 'Annullato'), ('completed', 'Completato')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Note del cliente')),
                ('notary_notes', models.TextField(blank=True, help_text='Note del notaio')),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='notaries.notary')),
            ],
            options={
                'verbose_name': 'Appuntamento',
                'verbose_name_plural': 'Appuntamenti',
                'db_table': 'appointments',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['notary', 'date', 'status'], name='appointment_notary__76362c_idx'), models.Index(fields=['client', 'status'], name='appointment_client__21adcd_idx')],
            },
        ),
    ]
