# Generated by Django 5.2.7 on 2025-10-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaries', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notary',
            name='license_active',
            field=models.BooleanField(default=True, help_text='Se False, il notaio può solo visualizzare dati esistenti, non creare nuovi appuntamenti'),
        ),
        migrations.AddField(
            model_name='notary',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='Data di scadenza della licenza', null=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='license_notes',
            field=models.TextField(blank=True, help_text='Note amministrative sulla licenza (rinnovi, comunicazioni, etc.)'),
        ),
        migrations.AddField(
            model_name='notary',
            name='license_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Importo del canone (es. 99.00 per mensile, 990.00 per annuale)', max_digits=10),
        ),
        migrations.AddField(
            model_name='notary',
            name='license_payment_frequency',
            field=models.CharField(choices=[('monthly', 'Mensile'), ('annual', 'Annuale')], default='annual', help_text='Frequenza di pagamento della licenza', max_length=20),
        ),
        migrations.AddField(
            model_name='notary',
            name='license_start_date',
            field=models.DateField(blank=True, help_text='Data di attivazione della licenza', null=True),
        ),
    ]
