# Generated by Django 5.2.7 on 2025-10-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaries', '0005_notary_license_active_notary_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notary',
            name='cellulare',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='notary',
            name='certificato_iscrizione_albo',
            field=models.FileField(blank=True, null=True, upload_to='notai/documenti/albo/'),
        ),
        migrations.AddField(
            model_name='notary',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='cognome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notary',
            name='data_iscrizione_albo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='distretto_notarile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notary',
            name='documento_identita',
            field=models.FileField(blank=True, null=True, upload_to='notai/documenti/identita/'),
        ),
        migrations.AddField(
            model_name='notary',
            name='email_studio',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='notary',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Se il notaio è stato verificato dall'admin"),
        ),
        migrations.AddField(
            model_name='notary',
            name='luogo_nascita',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notary',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notary',
            name='numero_iscrizione_albo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='orari_ricevimento',
            field=models.JSONField(blank=True, help_text='Orari di ricevimento in formato JSON (unified from Notaio)', null=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='partita_iva',
            field=models.CharField(blank=True, help_text='Partita IVA del notaio/studio', max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notary',
            name='sede_notarile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notary',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1),
        ),
        migrations.AddField(
            model_name='notary',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('notaio_singolo', 'Notaio Singolo'), ('studio_associato', 'Studio Associato'), ('societa_tra_professionisti', 'Società tra Professionisti')], default='notaio_singolo', max_length=30),
        ),
        migrations.AddField(
            model_name='notary',
            name='visura_camerale',
            field=models.FileField(blank=True, null=True, upload_to='notai/documenti/visura/'),
        ),
    ]
