# Generated by Django 5.2.7 on 2025-10-17 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acts', '0001_initial'),
        ('notaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('richiesto', 'Richiesto'), ('confermato', 'Confermato'), ('rifiutato', 'Rifiutato'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='richiesto', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='acts.act')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='notaries.client')),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='notaries.notary')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['notary', 'start_time'], name='appointment_notary__8beeb5_idx'), models.Index(fields=['client', 'start_time'], name='appointment_client__63cb01_idx'), models.Index(fields=['status', 'start_time'], name='appointment_status_12e0f2_idx')],
            },
        ),
    ]
