# Generated by Django 5.2.7 on 2025-10-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_notaio_partita_iva_alter_partner_partita_iva'),
        ('appointments', '0002_appuntamento_disponibilitanotaio_and_more'),
        ('notaries', '0007_migrate_notaio_to_notary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntamento',
            name='notary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appuntamenti_organizzati', to='notaries.notary'),
        ),
        migrations.AddField(
            model_name='disponibilitanotaio',
            name='notary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilita', to='notaries.notary'),
        ),
        migrations.AlterField(
            model_name='appuntamento',
            name='notaio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appuntamenti_organizzati_old', to='accounts.notaio'),
        ),
        migrations.AlterField(
            model_name='disponibilitanotaio',
            name='notaio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilita_old', to='accounts.notaio'),
        ),
    ]
