# Generated by Django 5.2.7 on 2025-10-21 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
        ('appointments', '0004_migrate_relations_to_notary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntamento',
            name='motivo_rifiuto',
            field=models.TextField(blank=True, help_text="Motivazione del rifiuto dell'appuntamento"),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='rifiutato_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='rifiutato_da',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='tipologia_atto',
            field=models.ForeignKey(blank=True, help_text="Tipologia di atto per cui è richiesto l'appuntamento", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appuntamenti_richiesti', to='acts.notarialactcategory'),
        ),
        migrations.AlterField(
            model_name='appuntamento',
            name='status',
            field=models.CharField(choices=[('provvisorio', 'Provvisorio'), ('richiesto', 'Richiesto'), ('confermato', 'Confermato'), ('rifiutato', 'Rifiutato'), ('documenti_in_caricamento', 'Documenti in Caricamento'), ('documenti_in_verifica', 'Documenti in Verifica'), ('documenti_parziali', 'Documenti Parzialmente Accettati'), ('documenti_verificati', 'Documenti Verificati'), ('pronto_atto_virtuale', 'Pronto per Atto Virtuale'), ('in_corso', 'In Corso'), ('completato', 'Completato'), ('annullato', 'Annullato'), ('approvato', 'Approvato')], default='provvisorio', max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentoAppuntamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, help_text='File del documento caricato dal cliente', null=True, upload_to='appuntamenti/documenti/%Y/%m/%d/')),
                ('stato', models.CharField(choices=[('da_caricare', 'Da Caricare'), ('caricato', 'Caricato'), ('in_verifica', 'In Verifica'), ('accettato', 'Accettato'), ('rifiutato', 'Rifiutato')], default='da_caricare', max_length=20)),
                ('is_obbligatorio', models.BooleanField(default=True, help_text='Se il documento è obbligatorio per questo appuntamento')),
                ('caricato_at', models.DateTimeField(blank=True, null=True)),
                ('verificato_at', models.DateTimeField(blank=True, null=True)),
                ('note_rifiuto', models.TextField(blank=True, help_text='Motivazione del rifiuto del documento')),
                ('note_interne', models.TextField(blank=True, help_text='Note visibili solo al notaio/staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appuntamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_appuntamento', to='appointments.appuntamento')),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_caricati', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(help_text='Tipo di documento richiesto', on_delete=django.db.models.deletion.CASCADE, related_name='documenti_appuntamenti', to='acts.documenttype')),
                ('verificato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_verificati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Appuntamento',
                'verbose_name_plural': 'Documenti Appuntamento',
                'db_table': 'documenti_appuntamento',
                'ordering': ['document_type__category', 'document_type__name'],
                'unique_together': {('appuntamento', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('appuntamento_richiesto', 'Nuova Richiesta Appuntamento'), ('appuntamento_confermato', 'Appuntamento Confermato'), ('appuntamento_rifiutato', 'Appuntamento Rifiutato'), ('appuntamento_modificato', 'Appuntamento Modificato'), ('appuntamento_annullato', 'Appuntamento Annullato'), ('appuntamento_reminder', 'Reminder Appuntamento'), ('documenti_da_caricare', 'Documenti da Caricare'), ('documento_caricato', 'Nuovo Documento Caricato'), ('documento_accettato', 'Documento Accettato'), ('documento_rifiutato', 'Documento Rifiutato'), ('documenti_verificati', 'Tutti i Documenti Verificati'), ('atto_virtuale_disponibile', 'Atto Virtuale Disponibile'), ('atto_creato', 'Nuovo Atto Creato'), ('atto_firmato', 'Atto Firmato'), ('atto_completato', 'Atto Completato'), ('messaggio_sistema', 'Messaggio di Sistema'), ('altro', 'Altro')], default='altro', max_length=50)),
                ('titolo', models.CharField(max_length=255)),
                ('messaggio', models.TextField()),
                ('link_url', models.CharField(blank=True, help_text='URL a cui reindirizzare quando si clicca la notifica', max_length=500)),
                ('letta', models.BooleanField(default=False)),
                ('letta_at', models.DateTimeField(blank=True, null=True)),
                ('invia_email', models.BooleanField(default=False, help_text='Se True, invia anche una email')),
                ('email_inviata', models.BooleanField(default=False)),
                ('email_inviata_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appuntamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='appointments.appuntamento')),
                ('atto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='acts.act')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'db_table': 'notifiche',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notifiche_user_id_e6382e_idx'), models.Index(fields=['user', 'letta', '-created_at'], name='notifiche_user_id_5cf915_idx'), models.Index(fields=['tipo', '-created_at'], name='notifiche_tipo_d27c92_idx')],
            },
        ),
    ]
