# Generated by Django 5.2.7 on 2025-10-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appuntamento_motivo_rifiuto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntamento',
            name='has_conservation',
            field=models.BooleanField(default=False, help_text='Conservazione sostitutiva'),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='has_digital_signature',
            field=models.BooleanField(default=False, help_text='Firma digitale'),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='has_documents',
            field=models.BooleanField(default=False, help_text='Gestione documenti'),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='has_shared_folder',
            field=models.BooleanField(default=False, help_text='Cartella condivisa'),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='is_in_person',
            field=models.BooleanField(default=False, help_text='Appuntamento in presenza'),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='is_phone',
            field=models.BooleanField(default=False, help_text='Chiamata telefonica'),
        ),
    ]
