# Generated by Django 5.2.7 on 2025-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appuntamento_has_conservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntamento',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dati aggiuntivi per la video chiamata e altre funzionalità'),
        ),
    ]
