# Generated by Django 5.2.7 on 2025-10-24 20:25

from django.db import migrations, models
import django.db.models.deletion


def migrate_cliente_refs(apps, schema_editor):
    """
    Migra i riferimenti da Cliente (accounts) a Client (notaries).
    """
    # Ottieni i modelli
    ClienteOld = apps.get_model('accounts', 'Cliente')
    ClientNew = apps.get_model('notaries', 'Client')
    PartecipanteAppuntamento = apps.get_model('appointments', 'PartecipanteAppuntamento')
    
    # Crea mapping Cliente vecchio → Client nuovo
    mapping = {}
    for old_client in ClienteOld.objects.all():
        try:
            new_client = ClientNew.objects.get(user=old_client.user)
            mapping[old_client.id] = new_client.id
        except ClientNew.DoesNotExist:
            print(f"⚠️  Client non trovato per user {old_client.user.email}")
    
    # Aggiorna i partecipanti (usando il mapping)
    updated_count = 0
    for partecipante in PartecipanteAppuntamento.objects.filter(cliente_id__isnull=False):
        old_id = partecipante.cliente_id
        if old_id in mapping:
            new_id = mapping[old_id]
            # Usa raw SQL per bypassare temporaneamente il constraint
            from django.db import connection
            with connection.cursor() as cursor:
                cursor.execute(
                    "UPDATE partecipanti_appuntamento SET cliente_id = %s WHERE id = %s",
                    [new_id, partecipante.id]
                )
            updated_count += 1
    
    print(f"✅ Migrati {updated_count} partecipanti")


def reverse_migrate(apps, schema_editor):
    """Reverse migration (non implementato perché irreversibile)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_add_metadata_field'),
        ('notaries', '0001_initial'),  # Assicura che il modello Client esista
    ]

    operations = [
        # Step 1: Rimuovi il constraint FK vecchio
        migrations.RunSQL(
            sql="ALTER TABLE partecipanti_appuntamento DROP CONSTRAINT IF EXISTS partecipanti_appuntamento_cliente_id_d39fb9d6_fk_clienti_id",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Step 2: Migra i dati
        migrations.RunPython(migrate_cliente_refs, reverse_migrate),
        
        # Step 3: Ricrea il constraint FK puntando alla nuova tabella
        migrations.AlterField(
            model_name='partecipanteappuntamento',
            name='cliente',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='appuntamenti_partecipati',
                to='notaries.client'
            ),
        ),
    ]
