# Generated by Django 5.2.7 on 2025-10-17 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acts', '0001_initial'),
        ('notaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PecTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(help_text='Usa {{variabile}} per placeholder')),
                ('variables', models.JSONField(default=list, help_text='["cliente_nome", "atto_numero", ...]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pec_templates', to='notaries.notary')),
            ],
            options={
                'verbose_name': 'PEC Template',
                'verbose_name_plural': 'PEC Templates',
                'db_table': 'pec_templates',
                'ordering': ['notary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PecMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_pec', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(help_text='[{"email": "...", "name": "...", "type": "to|cc|bcc"}, ...]')),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(default=list, help_text='[{"document_id": "...", "filename": "..."}, ...]')),
                ('status', models.CharField(choices=[('bozza', 'Bozza'), ('in_coda', 'In Coda'), ('inviato', 'Inviato'), ('consegnato', 'Consegnato'), ('errore', 'Errore'), ('quarantena', 'Quarantena')], default='bozza', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('receipt_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pec_messages', to='acts.act')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_pec_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='pec.pectemplate')),
            ],
            options={
                'verbose_name': 'PEC Message',
                'verbose_name_plural': 'PEC Messages',
                'db_table': 'pec_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['act', '-created_at'], name='pec_message_act_id_cbc703_idx'), models.Index(fields=['status'], name='pec_message_status_7d82e0_idx'), models.Index(fields=['sender'], name='pec_message_sender__45d2e5_idx')],
            },
        ),
    ]
