# Generated by Django 5.2.7 on 2025-10-17 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acts', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RtcSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('video_1to1', 'Video 1:1'), ('video_group', 'Video Group'), ('screen_share', 'Screen Share'), ('document_share', 'Document Share')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed')], default='active', max_length=20)),
                ('server_url', models.TextField(blank=True)),
                ('room_id', models.CharField(blank=True, max_length=255)),
                ('collaboration_state', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtc_sessions', to='acts.act')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('shared_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtc_sessions', to='documents.actdocument')),
            ],
            options={
                'verbose_name': 'RTC Session',
                'verbose_name_plural': 'RTC Sessions',
                'db_table': 'rtc_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RtcParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('can_share_screen', models.BooleanField(default=True)),
                ('can_edit_document', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rtc_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rtc.rtcsession')),
            ],
            options={
                'verbose_name': 'RTC Participant',
                'verbose_name_plural': 'RTC Participants',
                'db_table': 'rtc_participants',
                'ordering': ['session', 'joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rtcsession',
            index=models.Index(fields=['host', '-started_at'], name='rtc_session_host_id_fbde78_idx'),
        ),
        migrations.AddIndex(
            model_name='rtcsession',
            index=models.Index(fields=['status'], name='rtc_session_status_6e0281_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rtcparticipant',
            unique_together={('session', 'user')},
        ),
    ]
