# Generated by Django 5.2.7 on 2025-10-17 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('document_ids', models.JSONField(default=list, help_text='Array di document_id inclusi nel pacchetto')),
                ('conservator_provider', models.CharField(blank=True, help_text='Conservatore accreditato AgID', max_length=100)),
                ('conservator_package_id', models.CharField(blank=True, max_length=255)),
                ('package_hash', models.CharField(blank=True, max_length=64)),
                ('package_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('exported', 'Exported'), ('conserved', 'Conserved'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('conserved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conservation_packages', to='notaries.notary')),
            ],
            options={
                'verbose_name': 'Conservation Package',
                'verbose_name_plural': 'Conservation Packages',
                'db_table': 'conservation_packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
