# Generated by Django 5.2.7 on 2025-10-17 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_type', models.CharField(choices=[('cades', 'CAdES'), ('xades', 'XAdES'), ('pades', 'PAdES')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='es. "Infocert", "Aruba", "Namirial"', max_length=100)),
                ('provider_request_id', models.CharField(blank=True, max_length=255)),
                ('otp_sent', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='documents.actdocument')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_signatures', to=settings.AUTH_USER_MODEL)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature Request',
                'verbose_name_plural': 'Signature Requests',
                'db_table': 'signature_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimestampRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tsa_provider', models.CharField(blank=True, max_length=100)),
                ('tsa_response', models.BinaryField(blank=True)),
                ('timestamp_token', models.TextField(blank=True)),
                ('timestamp_value', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamp_requests', to='documents.actdocument')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_timestamps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timestamp Request',
                'verbose_name_plural': 'Timestamp Requests',
                'db_table': 'timestamp_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
