# Generated by Django 5.2.7 on 2025-10-17 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('anagrafica', 'Anagrafica'), ('banca', 'Banca'), ('permessi', 'Permessi'), ('certificazioni', 'Certificazioni'), ('catastali', 'Catastali'), ('urbanistici', 'Urbanistici'), ('contratti', 'Contratti'), ('allegati', 'Allegati'), ('firmati', 'Firmati'), ('altro', 'Altro')], max_length=20)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('blob_url', models.TextField()),
                ('blob_storage_key', models.CharField(max_length=500)),
                ('ciphertext_hash', models.CharField(max_length=64)),
                ('encryption_metadata', models.JSONField(default=dict, help_text='{"algorithm": "AES-256-GCM", "key_wrapped": true, ...}')),
                ('wrapped_keys', models.JSONField(default=list, help_text='[{"user_id": "...", "wrapped_key": "base64...", "algorithm": "RSA-OAEP"}, ...]')),
                ('version', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_type', models.CharField(blank=True, choices=[('cades', 'CAdES'), ('xades', 'XAdES'), ('pades', 'PAdES')], max_length=10, null=True)),
                ('signature_data', models.JSONField(blank=True, default=dict, help_text='{"signer": "...", "timestamp": "...", "certificate": "...", ...}')),
                ('has_timestamp', models.BooleanField(default=False)),
                ('timestamp_data', models.JSONField(blank=True, default=dict)),
                ('has_stamp', models.BooleanField(default=False)),
                ('stamp_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('access_log', models.JSONField(blank=True, default=list, help_text='[{"user_id": "...", "action": "download", "timestamp": "..."}, ...]')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='acts.act')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.actdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'act_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.actdocument')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Permission',
                'verbose_name_plural': 'Document Permissions',
                'db_table': 'document_permissions',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actdocument',
            index=models.Index(fields=['act', '-uploaded_at'], name='act_documen_act_id_9583d1_idx'),
        ),
        migrations.AddIndex(
            model_name='actdocument',
            index=models.Index(fields=['category', 'act'], name='act_documen_categor_53c9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='actdocument',
            index=models.Index(fields=['act', 'version', 'is_latest'], name='act_documen_act_id_10a6c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'user')},
        ),
    ]
