# Generated by Django 5.2.7 on 2025-10-25 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(help_text='Numero pagina (1-indexed)')),
                ('fabric_object', models.JSONField(help_text='Oggetto Fabric.js serializzato (canvas.toJSON())')),
                ('object_type', models.CharField(help_text='Tipo oggetto: text, path (disegno), rect, circle, line, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('z_index', models.IntegerField(default=0, help_text='Ordine di rendering')),
                ('created_by', models.ForeignKey(help_text="Utente che ha creato l'annotazione", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_annotations_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Documento PDF annotato', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.actdocument')),
            ],
            options={
                'verbose_name': 'PDF Annotation',
                'verbose_name_plural': 'PDF Annotations',
                'db_table': 'pdf_annotations',
                'ordering': ['document', 'page_number', 'z_index', 'created_at'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='pdf_annotat_documen_48bd53_idx'), models.Index(fields=['created_by'], name='pdf_annotat_created_1a55f8_idx')],
            },
        ),
    ]
