# Generated by Django 5.2.7 on 2025-10-17 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('identita', 'Documenti di Identità'), ('immobile', 'Documenti Immobile'), ('fiscale', 'Documenti Fiscali'), ('stato_civile', 'Stato Civile'), ('societario', 'Documenti Societari'), ('finanziario', 'Documenti Finanziari'), ('tecnico', 'Documenti Tecnici'), ('altro', 'Altro')], default='altro', max_length=50)),
                ('required_from', models.CharField(choices=[('cliente', 'Cliente'), ('venditore', 'Venditore'), ('acquirente', 'Acquirente'), ('entrambi', 'Entrambe le parti'), ('banca', 'Banca'), ('professionista', 'Professionista'), ('PA', 'Pubblica Amministrazione')], default='cliente', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Se obbligatorio o facoltativo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'db_table': 'document_types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotarialActMainCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'db_table': 'notarial_act_main_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotarialActCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within main category')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_property', models.BooleanField(default=False, help_text='Requires property data')),
                ('requires_bank', models.BooleanField(default=False, help_text='Requires bank data')),
                ('requires_parties', models.BooleanField(default=True, help_text='Requires parties data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='acts.notarialactmaincategory')),
            ],
            options={
                'verbose_name': 'Notarial Act Category',
                'verbose_name_plural': 'Notarial Act Categories',
                'db_table': 'notarial_act_categories',
                'ordering': ['main_category__order', 'order', 'name'],
                'unique_together': {('main_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('compravendita', 'Compravendita'), ('mutuo', 'Mutuo'), ('testamento', 'Testamento'), ('costituzione_societa', 'Costituzione Società'), ('donazione', 'Donazione'), ('divisione', 'Divisione'), ('successione', 'Successione'), ('procura', 'Procura'), ('altro', 'Altro')], max_length=30)),
                ('status', models.CharField(choices=[('bozza', 'Bozza'), ('in_lavorazione', 'In Lavorazione'), ('in_attesa_firma', 'In Attesa Firma'), ('firmato', 'Firmato'), ('inviato_pec', 'Inviato PEC'), ('archiviato', 'Archiviato'), ('annullato', 'Annullato')], default='bozza', max_length=30)),
                ('protocol_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('protocol_year', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('parties', models.JSONField(blank=True, default=list, help_text='[{"type": "venditore", "client_id": "...", "name": "..."}, ...]')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_branch', models.CharField(blank=True, max_length=255)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('property_address', models.CharField(blank=True, max_length=500)),
                ('property_cadastral_data', models.JSONField(blank=True, default=dict)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('signing_date', models.DateTimeField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('survey_completed', models.BooleanField(default=False)),
                ('survey_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='notaries.client')),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='notaries.notary')),
            ],
            options={
                'verbose_name': 'Act',
                'verbose_name_plural': 'Acts',
                'db_table': 'acts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notary', '-created_at'], name='acts_notary__e6bebf_idx'), models.Index(fields=['client', '-created_at'], name='acts_client__f31e16_idx'), models.Index(fields=['category', 'status'], name='acts_categor_6cebc3_idx'), models.Index(fields=['protocol_number', 'protocol_year'], name='acts_protoco_ec7c2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotarialActCategoryDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Se il documento è obbligatorio per questo atto')),
                ('notes', models.TextField(blank=True, help_text='Note specifiche per questo documento in questo atto')),
                ('order', models.IntegerField(default=0, help_text='Ordine di visualizzazione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='acts.notarialactcategory')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_categories', to='acts.documenttype')),
            ],
            options={
                'verbose_name': 'Act Category Document',
                'verbose_name_plural': 'Act Category Documents',
                'db_table': 'notarial_act_category_documents',
                'ordering': ['order', 'document_type__name'],
                'unique_together': {('act_category', 'document_type')},
            },
        ),
    ]
