# Generated by Django 5.2.7 on 2025-10-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarialactcategory',
            name='estimated_duration_minutes',
            field=models.IntegerField(default=60, help_text='Durata stimata in minuti per questo tipo di atto'),
        ),
    ]
