# Generated by Django 5.2.7 on 2025-10-26 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_notarialactcategory_estimated_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act_type_code', models.CharField(db_index=True, help_text='Codice della tipologia atto (es: rogito, donazione, testamento)', max_length=50)),
                ('act_type_name', models.CharField(help_text='Nome della tipologia atto', max_length=200)),
                ('code_prefix', models.CharField(db_index=True, help_text='Prefisso per la generazione codici atto (es: ATT-NT, DON, TEST)', max_length=20)),
                ('current_progressive', models.IntegerField(default=0, help_text='Ultimo numero progressivo utilizzato per questa tipologia')),
                ('template_file', models.FileField(help_text='File template (DOCX, PDF, ODT)', upload_to='templates/acts/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('description', models.TextField(blank=True, help_text='Descrizione del template e quando utilizzarlo')),
                ('usage_notes', models.TextField(blank=True, help_text="Note tecniche per l'utilizzo del template")),
                ('is_active', models.BooleanField(default=True, help_text='Se il template è attivo e utilizzabile')),
                ('version', models.CharField(default='1.0', help_text='Versione del template', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Act Template',
                'verbose_name_plural': 'Act Templates',
                'db_table': 'act_templates',
                'ordering': ['act_type_name', '-created_at'],
                'indexes': [models.Index(fields=['act_type_code', 'is_active'], name='act_templat_act_typ_d4527a_idx'), models.Index(fields=['code_prefix'], name='act_templat_code_pr_1cbe35_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('act_type_code',), name='unique_active_template_per_act_type')],
            },
        ),
    ]
