# Generated by Django 5.2.7 on 2025-10-26 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_acttemplate'),
        ('appointments', '0008_migrate_cliente_to_client'),
        ('notaries', '0007_migrate_notaio_to_notary_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolloAttoNotarile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_protocollo', models.CharField(db_index=True, help_text='Numero protocollo completo (es: TEST-0001)', max_length=50, unique=True)),
                ('tipologia_atto_code', models.CharField(db_index=True, max_length=100)),
                ('tipologia_atto_nome', models.CharField(max_length=200)),
                ('code_prefix', models.CharField(help_text='Prefisso codice (es: TEST)', max_length=20)),
                ('progressivo', models.IntegerField(help_text='Numero progressivo per questa tipologia')),
                ('parti_coinvolte', models.JSONField(default=dict, help_text='Dati delle parti (cliente, eventuali altre parti)')),
                ('documento_finale_url', models.FileField(blank=True, help_text='Documento finale firmato', null=True, upload_to='atti_protocollati/%Y/%m/')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('in_lavorazione', 'In Lavorazione'), ('pronto_firma', 'Pronto per Firma'), ('firmato', 'Firmato'), ('protocollato', 'Protocollato'), ('annullato', 'Annullato')], db_index=True, default='bozza', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e ora di creazione (data certa)')),
                ('data_firma', models.DateTimeField(blank=True, help_text='Data e ora della firma digitale', null=True)),
                ('data_protocollo', models.DateTimeField(blank=True, db_index=True, help_text='Data e ora di protocollazione definitiva', null=True)),
                ('data_annullamento', models.DateTimeField(blank=True, null=True)),
                ('motivo_annullamento', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadati aggiuntivi (importo, immobili, ecc.)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appuntamento', models.OneToOneField(help_text='Appuntamento collegato a questo atto', on_delete=django.db.models.deletion.PROTECT, related_name='protocollo_atto', to='appointments.appuntamento')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolli_creati', to=settings.AUTH_USER_MODEL)),
                ('notaio', models.ForeignKey(help_text="Notaio responsabile dell'atto", on_delete=django.db.models.deletion.PROTECT, related_name='atti_protocollati', to='notaries.notary')),
                ('template', models.ForeignKey(help_text='Template utilizzato per questo atto', on_delete=django.db.models.deletion.PROTECT, related_name='protocolli_generati', to='acts.acttemplate')),
            ],
            options={
                'verbose_name': 'Protocollo Atto Notarile',
                'verbose_name_plural': 'Protocolli Atti Notarili',
                'db_table': 'acts_protocollo_atto_notarile',
                'ordering': ['-data_creazione'],
                'indexes': [models.Index(fields=['tipologia_atto_code', '-progressivo'], name='acts_protoc_tipolog_0f0419_idx'), models.Index(fields=['notaio', '-data_creazione'], name='acts_protoc_notaio__429f63_idx'), models.Index(fields=['stato', '-data_creazione'], name='acts_protoc_stato_d36107_idx'), models.Index(fields=['-data_protocollo'], name='acts_protoc_data_pr_5b6751_idx')],
            },
        ),
    ]
